spring:
  application:
    name: newkitchensink

server:
  servlet:
    context-path: /newkitchensink/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip: true